#!/bin/bash

entries="Logout Suspend Reboot Shutdown Lock"

selected=$(printf '%s\n' $entries | wofi --conf=$HOME/.config/wofi/config.menu --lines=5 --style=$HOME/.config/wofi/style.menu.css | awk '{print tolower($1)}')

case $selected in
  logout)
    swaymsg exit;;
  suspend)
    exec systemctl suspend;;
  reboot)
    exec systemctl reboot;;
  shutdown)
    exec systemctl poweroff -i;;
  lock)
    ~/.config/sway/scripts/lock;;
esac